pub const ORDER_MARGIN: f32 = 20.0; // 유닛이 목표 지점에 도달했다고 간주하는 거리
pub const NEAR_TARGET_MARGIN: f32 = 60.0; // 유닛이 목표 지점 근처에 있다고 간주하는 거리
pub const SEARCH_RADIUS: f32 = 50.0; // 주변 유닛 탐색 반경
pub const OBSTACLE_MARGIN: f32 = 5.0; // 장애물 회피를 위한 마진
pub const TIME_HORIZON: f32 = 1.0; // 회피 계산 시 예측 시간
pub const STOP_DELAY: f32 = 0.25; // 명령 완료 후 유닛이 멈추기까지의 지연 시간
pub const STOP_COL_MARGIN: f32 = 5.0; // 명령 완료한 유닛과 충돌 판정 시 마진S
pub const RETURN_TO_STOP_MARGIN: f32 = 20.0; // 명령 완료 후 유닛이 멈춘 위치로 돌아갈 때의 마진
pub const STOP_RENEW_DELAY: f32 = 1.0; // 멈춘 위치 갱신 지연 시간
pub const MOVING_RESP: f32 = 0.5;
pub const STOP_RESP: f32 = 2.0;
pub const CELL_SIZE: f32 = 40.0; // 플로우 필드 및 공간 분할 그리드의 셀 크기
