[package]
name = "game-backend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.102"
bevy_ecs = { version = "0.18.1", features = ["debug"] }
chunk-flow-field = "0.1.1"
dodgy_2d = "0.5.5"
godot = "0.5.4"
rayon = "1.11.0"
strum = { version = "0.28.0", features = ["derive"] }
